# Generated by Django 5.2.7 on 2025-10-16 16:28

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=40)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido', max_length=50)),
                ('ussername', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='UsserName', max_length=20, unique=True)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Correo', max_length=30)),
                ('contraseña', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Contraseña', max_length=50)),
                ('is_active', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriainsumos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('estado', models.BooleanField(db_column='Estado')),
                ('categoriainsumo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='CategoriaInsumo', max_length=50)),
            ],
            options={
                'db_table': 'CategoriaInsumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('nombrecultivo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreCultivo', max_length=50)),
                ('fechasiembra', models.DateTimeField(db_column='FechaSiembra')),
                ('fechacosecha', models.DateTimeField(blank=True, db_column='FechaCosecha', null=True)),
                ('area_m2', models.DecimalField(db_column='Area_m2', decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Cultivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleinsumosusados',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8)),
                ('cantidadusada', models.DecimalField(db_column='CantidadUsada', decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'DetalleInsumosUsados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Modern_Spanish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('insumo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Insumo', max_length=50)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('fechacaducidad', models.DateTimeField(db_column='FechaCaducidad')),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimientocultivos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('nombretipomantenimiento', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreTipoMantenimiento', max_length=50)),
                ('fechamantenimiento', models.DateTimeField(db_column='FechaMantenimiento')),
                ('descripcionmantenimiento', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DescripcionMantenimiento', max_length=400, null=True)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'MantenimientoCultivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitoreosuelos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('humedad', models.DecimalField(db_column='Humedad', decimal_places=2, max_digits=5)),
                ('ph', models.DecimalField(db_column='pH', decimal_places=2, max_digits=4)),
                ('nitrogeno', models.DecimalField(blank=True, db_column='Nitrogeno', decimal_places=2, max_digits=4, null=True)),
                ('fechamonitoreo', models.DateTimeField(db_column='FechaMonitoreo')),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'MonitoreoSuelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('rol', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Rol', max_length=20)),
                ('descripcionrol', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DescripcionRol', max_length=150, null=True)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suelos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=30)),
                ('area_m2', models.DecimalField(db_column='Area_m2', decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Suelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suelos_Cultivos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Suelos_Cultivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadesmedida',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=8, unique=True)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=20)),
                ('estado', models.BooleanField(db_column='Estado')),
                ('abreviatura', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Abreviatura', max_length=4)),
            ],
            options={
                'db_table': 'UnidadesMedida',
                'managed': False,
            },
        ),
    ]
