# Generated by Django 5.2.7 on 2025-10-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosechas',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fechacosecha', models.DateTimeField(db_column='FechaCosecha')),
                ('cantidadrecogida', models.DecimalField(db_column='CantidadRecogida', decimal_places=2, max_digits=10)),
                ('calidad', models.CharField(blank=True, db_column='Calidad', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'db_table': 'Cosechas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostosCosecha',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fechacosto', models.DateField(db_column='FechaCosto')),
                ('montocosto', models.DecimalField(db_column='MontoCosto', decimal_places=2, max_digits=12)),
                ('tipocosto', models.CharField(db_column='TipoCosto', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'db_table': 'CostosCosecha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fechaingreso', models.DateField(db_column='FechaIngreso')),
                ('montoingreso', models.DecimalField(db_column='MontoIngreso', decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'db_table': 'Ingresos',
                'managed': False,
            },
        ),
    ]
